### ISSUE TITLE
extract and test phases of the algorithm separately

### ISSUE THREAD

**Issue by mischkew** [platener/GreinerHormann#4]
- [x] find intersections #1 
- [x] label entry/ exit points #6 
- [ ] build up list of clipped polygons #7 
- [x] return either clip or source if no clipped area #8
